language: node_js

branches:
  only:
    - master

node_js:
  - "0.10"
  - "0.11"

branches:
  only:
    - master

before_script:
  - "npm install -g gulp"
  - "npm install"

script:
  - "npm run build"

notifications:
  email:
    - ram@hiddentao.com